# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
minecraft_version=1.21.1
enabled_platforms=fabric,forge
archives_base_name=master-weapons
mod_version=3.3.0
maven_group=com.ultreon.mods
architectury_version=9.2.14
fabric_loader_version=0.14.21
fabric_api_version=0.92.9+1.20.1
forge_version=1.20.1-47.4.5
